name              'mariadb-enterprise-devel'
maintainer        'MariaDB, Inc.'
maintainer_email  'Andrey.Kuznetsov@mariadb.com'
license           'Apache 2.0'
description       'MariaDB development coockbook (internal)'
version           '0.0.2'
recipe            'develop', 'Prepares environment to build MariaDB'
recipe            'galera_dev', 'Prepares environment to build Galera for MDB cluster'
recipe            'install', 'Installs Enterprise edition'
recipe            'uninstall', 'Uninstalls any edition'
recipe            'purge', 'Uninstalls any edition and remove all data'
recipe            'start', 'Creates new instance of service and starts it'
recipe            'stop', 'Creates new instance of service and starts it'

supports          'redhat'
supports          'centos'
supports          'fedora'
supports          'debian'
supports          'ubuntu'
supports          'suse'

